// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: accounts_accounttypes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountTypeToAccount = `-- name: AddAccountTypeToAccount :exec
INSERT INTO "user_service"."Accounts_AccountTypes" ("Accounts_id", "AccountTypes_id")
VALUES ($1, $2)
`

type AddAccountTypeToAccountParams struct {
	AccountsID     int64 `json:"Accounts_id"`
	AccountTypesID int64 `json:"AccountTypes_id"`
}

func (q *Queries) AddAccountTypeToAccount(ctx context.Context, arg AddAccountTypeToAccountParams) error {
	_, err := q.db.Exec(ctx, addAccountTypeToAccount, arg.AccountsID, arg.AccountTypesID)
	return err
}

const getAccountTypeIDsForAccount = `-- name: GetAccountTypeIDsForAccount :many
SELECT at.id, at.created_at, at.updated_at FROM "user_service"."AccountTypes" at
JOIN "user_service"."Accounts_AccountTypes" aat ON at.id = aat."AccountTypes_id"
WHERE aat."Accounts_id" = $1
`

type GetAccountTypeIDsForAccountRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAccountTypeIDsForAccount(ctx context.Context, accountsID int64) ([]GetAccountTypeIDsForAccountRow, error) {
	rows, err := q.db.Query(ctx, getAccountTypeIDsForAccount, accountsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountTypeIDsForAccountRow{}
	for rows.Next() {
		var i GetAccountTypeIDsForAccountRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountTypesForAccount = `-- name: GetAccountTypesForAccount :many
SELECT at.id, at.description, at.permissions, at.is_artist, at.is_producer, at.is_writer, at.is_label, at.created_at, at.updated_at FROM "user_service"."AccountTypes" at
JOIN "user_service"."Accounts_AccountTypes" aat ON at.id = aat."AccountTypes_id"
WHERE aat."Accounts_id" = $1
`

func (q *Queries) GetAccountTypesForAccount(ctx context.Context, accountsID int64) ([]UserServiceAccountType, error) {
	rows, err := q.db.Query(ctx, getAccountTypesForAccount, accountsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserServiceAccountType{}
	for rows.Next() {
		var i UserServiceAccountType
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Permissions,
			&i.IsArtist,
			&i.IsProducer,
			&i.IsWriter,
			&i.IsLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsForAccountType = `-- name: GetAccountsForAccountType :many
SELECT ac.id, ac.username, ac.email, ac.country_code, ac.avatar_url, ac.likes_count, ac.follows_count, ac.created_at, ac.updated_at FROM "user_service"."Accounts" ac
JOIN "user_service"."Accounts_AccountTypes" aat ON ac.id = aat."Accounts_id"
WHERE aat."AccountTypes_id" = $1
`

type GetAccountsForAccountTypeRow struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	CountryCode  string             `json:"country_code"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	LikesCount   int64              `json:"likes_count"`
	FollowsCount int64              `json:"follows_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAccountsForAccountType(ctx context.Context, accounttypesID int64) ([]GetAccountsForAccountTypeRow, error) {
	rows, err := q.db.Query(ctx, getAccountsForAccountType, accounttypesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsForAccountTypeRow{}
	for rows.Next() {
		var i GetAccountsForAccountTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CountryCode,
			&i.AvatarUrl,
			&i.LikesCount,
			&i.FollowsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAccountTypeFromAccount = `-- name: RemoveAccountTypeFromAccount :exec
DELETE FROM "user_service"."Accounts_AccountTypes"
WHERE "Accounts_id" = $1 AND "AccountTypes_id" = $2
`

type RemoveAccountTypeFromAccountParams struct {
	AccountsID     int64 `json:"Accounts_id"`
	AccountTypesID int64 `json:"AccountTypes_id"`
}

func (q *Queries) RemoveAccountTypeFromAccount(ctx context.Context, arg RemoveAccountTypeFromAccountParams) error {
	_, err := q.db.Exec(ctx, removeAccountTypeFromAccount, arg.AccountsID, arg.AccountTypesID)
	return err
}

const removeAllRelationshipsForAccountAccountType = `-- name: RemoveAllRelationshipsForAccountAccountType :exec
DELETE FROM "user_service"."Accounts_AccountTypes"
WHERE "Accounts_id" = $1
`

func (q *Queries) RemoveAllRelationshipsForAccountAccountType(ctx context.Context, accountsID int64) error {
	_, err := q.db.Exec(ctx, removeAllRelationshipsForAccountAccountType, accountsID)
	return err
}

const removeAllRelationshipsForAccountTypeAccount = `-- name: RemoveAllRelationshipsForAccountTypeAccount :exec
DELETE FROM "user_service"."Accounts_AccountTypes"
WHERE "AccountTypes_id" = $1
`

func (q *Queries) RemoveAllRelationshipsForAccountTypeAccount(ctx context.Context, accounttypesID int64) error {
	_, err := q.db.Exec(ctx, removeAllRelationshipsForAccountTypeAccount, accounttypesID)
	return err
}
