// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: accounttype.sql

package db

import (
	"context"
)

const createAccountType = `-- name: CreateAccountType :one
INSERT INTO "user_svc"."AccountTypes" (
 type,
 permissions,
 is_artist,
 is_producer,
 is_writer,
 is_label
) VALUES (
 $1, $2, $3, $4, $5, $6
)
RETURNING id, type, permissions, is_artist, is_producer, is_writer, is_label, created_at, updated_at
`

type CreateAccountTypeParams struct {
	Type        string `json:"type"`
	Permissions []byte `json:"permissions"`
	IsArtist    bool   `json:"is_artist"`
	IsProducer  bool   `json:"is_producer"`
	IsWriter    bool   `json:"is_writer"`
	IsLabel     bool   `json:"is_label"`
}

func (q *Queries) CreateAccountType(ctx context.Context, arg CreateAccountTypeParams) (UserSvcAccountType, error) {
	row := q.db.QueryRow(ctx, createAccountType,
		arg.Type,
		arg.Permissions,
		arg.IsArtist,
		arg.IsProducer,
		arg.IsWriter,
		arg.IsLabel,
	)
	var i UserSvcAccountType
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Permissions,
		&i.IsArtist,
		&i.IsProducer,
		&i.IsWriter,
		&i.IsLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountType = `-- name: DeleteAccountType :exec
DELETE FROM "user_svc"."AccountTypes"
WHERE id = $1
`

func (q *Queries) DeleteAccountType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccountType, id)
	return err
}

const getAccountType = `-- name: GetAccountType :one
SELECT id, type, permissions, is_artist, is_producer, is_writer, is_label, created_at, updated_at FROM "user_svc"."AccountTypes"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountType(ctx context.Context, id int32) (UserSvcAccountType, error) {
	row := q.db.QueryRow(ctx, getAccountType, id)
	var i UserSvcAccountType
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Permissions,
		&i.IsArtist,
		&i.IsProducer,
		&i.IsWriter,
		&i.IsLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountTypes = `-- name: ListAccountTypes :many
SELECT id, type, permissions, is_artist, is_producer, is_writer, is_label, created_at, updated_at FROM "user_svc"."AccountTypes"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAccountTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccountTypes(ctx context.Context, arg ListAccountTypesParams) ([]UserSvcAccountType, error) {
	rows, err := q.db.Query(ctx, listAccountTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSvcAccountType{}
	for rows.Next() {
		var i UserSvcAccountType
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Permissions,
			&i.IsArtist,
			&i.IsProducer,
			&i.IsWriter,
			&i.IsLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountType = `-- name: UpdateAccountType :one
UPDATE "user_svc"."AccountTypes"
SET 
 type = COALESCE($2, type),
 permissions = COALESCE($3, permissions),
 is_artist = COALESCE($4, is_artist),
 is_producer = COALESCE($5, is_producer),
 is_writer = COALESCE($6, is_writer),
 is_label = COALESCE($7, is_label),
 updated_at = NOW()
WHERE id = $1
RETURNING id, type, permissions, is_artist, is_producer, is_writer, is_label, created_at, updated_at
`

type UpdateAccountTypeParams struct {
	ID          int32  `json:"id"`
	Type        string `json:"type"`
	Permissions []byte `json:"permissions"`
	IsArtist    bool   `json:"is_artist"`
	IsProducer  bool   `json:"is_producer"`
	IsWriter    bool   `json:"is_writer"`
	IsLabel     bool   `json:"is_label"`
}

func (q *Queries) UpdateAccountType(ctx context.Context, arg UpdateAccountTypeParams) (UserSvcAccountType, error) {
	row := q.db.QueryRow(ctx, updateAccountType,
		arg.ID,
		arg.Type,
		arg.Permissions,
		arg.IsArtist,
		arg.IsProducer,
		arg.IsWriter,
		arg.IsLabel,
	)
	var i UserSvcAccountType
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Permissions,
		&i.IsArtist,
		&i.IsProducer,
		&i.IsWriter,
		&i.IsLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
