// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSvcAccount struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CountryCode  string             `json:"country_code"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	LikesCount   int64              `json:"likes_count"`
	FollowsCount int64              `json:"follows_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserSvcAccountType struct {
	ID          int64              `json:"id"`
	Description pgtype.Text        `json:"description"`
	Permissions []byte             `json:"permissions"`
	IsArtist    bool               `json:"is_artist"`
	IsProducer  bool               `json:"is_producer"`
	IsWriter    bool               `json:"is_writer"`
	IsLabel     bool               `json:"is_label"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserSvcAccountsAccountType struct {
	AccountsID     int64 `json:"Accounts_id"`
	AccountTypesID int64 `json:"AccountTypes_id"`
}
