// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSvcSession struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserSvcUser struct {
	ID                int64       `json:"id"`
	Username          string      `json:"username"`
	FullName          string      `json:"full_name"`
	Email             string      `json:"email"`
	PasswordHash      string      `json:"password_hash"`
	PasswordSalt      string      `json:"password_salt"`
	CountryCode       string      `json:"country_code"`
	RoleID            pgtype.Int8 `json:"role_id"`
	Status            pgtype.Text `json:"status"`
	LastLoginAt       time.Time   `json:"last_login_at"`
	UsernameChangedAt time.Time   `json:"username_changed_at"`
	EmailChangedAt    time.Time   `json:"email_changed_at"`
	PasswordChangedAt time.Time   `json:"password_changed_at"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}
