// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSvcSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserSvcUser, error)
	DeleteUserById(ctx context.Context, id int64) error
	DeleteUserByValue(ctx context.Context, username string) error
	GetSession(ctx context.Context, id uuid.UUID) (UserSvcSession, error)
	GetUserById(ctx context.Context, id int64) (UserSvcUser, error)
	GetUserByValue(ctx context.Context, username string) (UserSvcUser, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UserSvcUser, error)
}

var _ Querier = (*Queries)(nil)
